### ISSUE TITLE
how to read fasta file

### ISSUE THREAD

**Issue by mbk0asis** [richelbilderbeek/netmhc2pan#2]
Hi.

I'm trying to run netmhc2pan, but having hard time to read my fasta file.

I've formatted the input to FASTA as shown below.

```
>PRDM16
FPPPDEQLLTATGATGDSIKAIASIAEKY
>PTPRF
PGITYSLRVLAFTAMGDGPPSPTIQVKTQ
>BCL9
GLYTHPGPVGSPGMLMSMQGMMGPQQNIM
```

then I read the file 
```
fasta_mut <- read.delim("example.fasta", header=F)
```

ran netmhc2pan

```
bindings <- run_netmhc2pan(
  fasta_filename = fasta_mut,
  alleles = alleles
)
```

It returned 
```
Error in file.exists(fasta_filename) : invalid 'file' argument
```

Is there a specific tool to read fasta file?

Thank you!

**Comment by richelbilderbeek** [comment]
Hi @mbk0asis,

The argument `fasta_filename` denotes you have to pass it the filename. No need for you reading that file youself first :grin: :+1:.

Something like this:

```r
bindings <- run_netmhc2pan(
  fasta_filename = "example.fasta",
  alleles = alleles
)
```

If this fixed your problems, go ahead and close this Issue :+1:

**Comment by mbk0asis** [comment]
It works!
Thank you for the quick reply and developing a great tool!
