### ISSUE TITLE
file.exists(netmhc2pan_bin_tarfile_path)

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/netmhc2pan#6]
Email from a user:

> I've attempted a local install from files, after downloading them from DTU healthtech, and followed the manual. But each time I 
> try I get an error saying: 'file.exists(netmhc2pan_bin_tarfile_path) is not TRUE.'

**Comment by JakubPalinski** [comment]
Here's the code:

library(netmhc2pan)
install_netmhc2pan_bin_from_file(
  netmhc2pan_bin_tarfile_path,
  verbose = FALSE,
  netmhc2pan_archive_filename = get_netmhc2pan_archive_filename(),
  netmhc2pan_folder_name = get_default_netmhc2pan_folder()
)

Error message in response: 

Error in file.exists(netmhc2pan_bin_tarfile_path) : 
  object 'netmhc2pan_bin_tarfile_path' not found

For more context:

get_default_netmhc2pan_bin_tarfile_path() returns:
"~/.local/share/netMHCIIpan-3.2.Linux.tar.gz"

**Comment by richelbilderbeek** [comment]
Checking the function signature used:


```
?netmhc2pan::install_netmhc2pan_bin_from_file
```

gives

```
     install_netmhc2pan_bin_from_file(
       netmhc2pan_bin_tarfile_path,
       verbose = FALSE,
       netmhc2pan_archive_filename = get_netmhc2pan_archive_filename(),
       netmhc2pan_folder_name = get_default_netmhc2pan_folder()
     )
```

That is OK.

Uhhh, this means my leading hypothesis is that the error message is just as expected: `netmhc2pan_bin_tarfile_path` simply does not exists.

@JakubPalinski could you run this code and give me back the results? It's a simplified version of yours :-)

```R
netmhc2pan_bin_tarfile_path <- ... # Fill in your path here
testthat::expect_true(file.exists(netmhc2pan_bin_tarfile_path)) # I predict this will fail

netmhc2pan::install_netmhc2pan_bin_from_file(
  netmhc2pan_bin_tarfile_path
)
```

**Comment by richelbilderbeek** [comment]
Maybe I should add a more expressive error message, so users are not thinking this is some advanced thing...

**Comment by JakubPalinski** [comment]
The result is the same, 

"Error: file.exists(netmhc2pan_bin_tarfile_path) is not TRUE."

**Comment by richelbilderbeek** [comment]
In case you cannot infer what that means (which is fine :-) ), do this:

```
remotes::install_github("richelbilderbeek/netmhc2pan", ref = "develop")
```

Then re-run your code. It will give you are more helpful error message. If you still cannot find the solution, let me know :-)

**Comment by richelbilderbeek** [comment]
From the user:


> I've had a look through the error messages and tried every iteration of the path that I know of. [...] but the path, I should set it to the downloaded software .gz file or is it something different?

You should set `netmhc2pan_bin_tarfile_path` to the path of the downloaded `.tar.gz` file. Please, show code :-)

**Comment by JakubPalinski** [comment]
Hi,

Issue resolved, this was on my end in terms of the path file name. Thank you very much for the help. :)

**Comment by richelbilderbeek** [comment]
Happy to help! Looking forward to a next bug report :-)

**Comment by richelbilderbeek** [comment]
Postmortem: the user used an incorrect path. This is not a problem of `netmhc2pan`. I improved the error message to make it more clear that the path is the problem.

Done!
